config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :users , only: [:new, :create, :index]

  root to: 'login#index'

  resources :items, only: [:index, :create, :destroy]
  resources :likes
  resources :dislikes


  resources :matches do
    resources :messages
  end

  resources :conversations do
    resources :messages,  :path => ''
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_disliked, :class_name => 'Item'
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessor :test
  belongs_to :user
  has_many :likes#, dependent: :destroy
  has_many :dislikes#, dependent: :destroy
  has_many :matches, foreign_key: "item_offered_id", dependent: :destroy
  mount_uploader :picture_url, ImageUploader
  public
  
  def self.test
    items = Item.all

    items.each{|item|
      item.remote_picture_url_url = item.url
      item.save
    }
  end
  def get_all_item_matches
    result_id = []
    item_matches = Match.where("item_offered_id = ? or item_liked_id = ?", self.id, self.id)
    item_matches.each do |item|
      if item.item_offered_id == self.id
        result_id << item.item_liked_id
      else
        result_id << item.item_offered_id
      end
    end
    Item.find(result_id)
  end
  #gets all the items that have liked this item
  def get_all_potential_trades
    result = Like.where("item_liked_id = ?", self.id).pluck(:item_offered_id)
    potential = Item.find(result)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_liked, :class_name => 'Item'
  after_save :check_matches

  def check_matches
    #search likes for inverse of item ids
    result = Like.where(:item_offered=>self.item_liked).where(:item_liked=>self.item_offered)
    #if results > 0, then insert a match in the matches table
    Match.create(item_offered: self.item_offered, item_liked: self.item_liked, user_offered: self.item_offered.user, user_liked: self.item_liked.user) if result.length > 0
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :user_offered, :class_name => 'User'
  belongs_to :user_liked, :class_name => 'User'
  belongs_to :item_offered, :class_name => 'Item'
  belongs_to :item_liked, :class_name => 'Item'
end

app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 def message_time
  created_at.strftime("%m/%d/%y at %l:%M %p")
 end
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :ip_address

  has_many :items
  has_many :likes#, dependent: :destroy
  has_many :dislikes#, dependent: :destroy
  has_many :liked_items, through: :likes, class_name: 'Item', source: :item
  has_many :disliked_items, through: :dislikes, class_name: 'Item', source: :item
  has_many :conversations, :foreign_key => :sender_id  # has_many :sender, foreign_key: 'user_sender_id', :class_name => 'Message'
  # has_many :receiver, foreign_key: 'user_receiver_id', :class_name => 'Message'
  geocoded_by :ip_address   # can also be an IP address
  after_validation :geocode

  def self.from_omniauth(auth)
    where(uid: auth.uid).first_or_create do |user|
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.email    = auth.info.email
      user.picture_profile_url = auth.info.image
      user.save
    end
  end

  def get_all_user_items
    myItems = Item.where(:user_id=>self.id)
    myItems
  end
  # Displays the conversations with the matched users
  def get_all_user_conversations
    contacts_part_one = Match.where("user_liked_id = ?", self.id).pluck(:user_offered_id)
    contacts_part_two = Match.where("user_offered_id = ?", self.id).pluck(:user_liked_id)
    a = User.find(contacts_part_one)
    b = User.find(contacts_part_two)
    c = a + b
    c
  end
  def get_nearby_items(distance)
    pp distance
    d = distance.to_i * 400
    items_near_me = []
    items_arr = []
    users_near_me = self.nearbys(d).shuffle
    users_near_me.each do |user|
      items_arr << Item.where('user_id = ?', user.id)
    end
    items_arr.each do |items|
      items.each do |item|
        items_near_me << item
      end
    end
    items_near_me

  end
  def get_all_messages_by_user(user)
    user1_id = self.id
    user2_id = user.id
    Message.where('(user_sender_id = ? and user_receiver_id = ?) or
    (user_sender_id = ? and user_receiver_id = ?)', user1_id,user2_id,user2_id,user1_id).order('created_at')
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :json, :html
  def index
   if current_user
     if params[:filter] == '1'
       @item = item_filter(Item.where('user_id <> ? ', current_user.id), params[:current_item_id])
     elsif params[:filter] == '2'
       @item = item_filter(current_user.get_nearby_items(params[:distance]), params[:current_item_id])
     end
     pp '============Test==========='
     pp params[:filter]
     pp @item
     respond_with(@item)
   else
     redirect_to root_url
   end
 end
  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to :back
    end
  end
  def show
    redirect_to items_path
  end
  def item_params
    params.require(:item).permit(:name, :picture_url, :description, :user_id, :remote_picture_url_url)
  end

  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    redirect_to :action => 'index'
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  respond_to :json, :html


  def create
    @like = Like.new({item_offered_id: params['item_offered_id'], item_liked_id: params['item_liked_id']})
    if @like.save
      render json: @like.check_matches
    end
  end

  def show
    redirect_to items_path
  end

  def like_params
    params.require(:like).permit(:item_offered_id, :item_liked_id)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    # if current_user
    #   redirect_to items_path
    # else
    #    redirect_to root_path
    # end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/swipe_controller.rb
class SwipeController < ApplicationController
  def findstuff
    @items = current_user.get_all_user_items
    @otheritems = Item.all - current_user.get_all_user_items
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html

  def new
    @user = User.new
  end

  def create
    @user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    if @user.save
      # Handle a successful save.
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  def index
    @user = current_user
    @items = current_user.get_all_user_items
    @current_item = current_item
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/swipe_helper.rb
module SwipeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<div class="modal" id="item-modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box">
      <div class="content">
        <h1>Add Your Item</h1>
        <%= form_for @item = Item.new, :html => {:multipart => true} do |f| %>

          <p>
            <%= f.label :name %><br />
            <%= f.text_field :name %>
          </p>
          <p>
            <%= f.label :description %><br />
            <%= f.text_area :description, :rows => 5, :cols => 45 %>
          </p>
          <p>
            <%= f.file_field :picture_url %>
          </p>
          <p>
            <%= f.label :remote_picture_url_url, "or image URL" %><br />
            <%= f.text_field :remote_picture_url_url %>
          </p>
          <p><%= f.submit %></p>
        <% end %>
      </div>
    </div>
  </div>
  <button class="modal-close" id="item-modal-close"></button>
</div>

app/views/items/_match_form.html.erb
<div class="modal" id="match-modal">
  <div class="modal-background"></div>
  <div class="modal-content">
    <div class="box">
      <div class="content">
        <div class="notification is-danger">
          <h2 class="title is-2"><strong>Match<strong></h2>
          </div>
          <div class="columns">
            <div class="column">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <img id="match-offered-item">
                  </figure>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-content">
                      <p class="title is-5" id="match-offered-title"></p>

                    </div>
                  </div>

                  <div class="content">
                    <p id="match-offered-desc"></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="column">
              <div class="card">
                <div class="card-image">
                  <figure class="image is-4by3">
                    <img id="match-liked-item">
                  </figure>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-content">
                      <p class="title is-5" id="match-liked-title"> </p>
                    </div>
                  </div>

                  <div class="content">
                    <p id="match-liked-desc"> </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="menu-block">
            <button class="button is-primary is-danger is-fullwidth" onclick="location.href='/matches';">
              Matches
            </button>
          </div>
        </div>
      </div>
      <button class="modal-close" id="match-modal-close"></button>
    </div>
  </div>

app/views/items/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <title>Find Stuff :)</title>



</head>
<body style= "zoom: 1;" id="items" data-user-id="<%= current_user.id %>" >
  <div class="container">
    <h2 class="subtitle is-2"><i class="fa fa-search"></i> Find Items</h2>

    <div class="columns">
      <div class="column is-2">
        <nav class="menu">
          <p class="menu-heading">
            <i class="fa fa-exchange"></i> My Items

          </p>
          <% user = current_user
          user_items = user.items
          user_items.each {|item| %>
            <a class="menu-block" id="item-menu" data-item-desc = "<%= item.description%>" data-item-id = "<%= item.id%>" data-thumb-picture="<%=item.picture_url.thumb.url%>" data-item-name="<%=item.name%>" href="#"><span class="menu-icon"><i class="image is-16x16"> <img src="<%=item.picture_url.mini.url %>" ></i></span><%= item.name%><%= link_to 'Delete', item_path(item), :method => :delete %></a>
            <% } %>
            <div class="menu-block">
              <button class="button is-primary is-outlined is-fullwidth" id="button-add-item">
                Add Item
              </button>
            </div>
          </nav>
        </div>
        <div class="column is-auto" id="touchsurface2">
          <div class="media">
            <div class="media-left">
              <figure class="image is-64x64" id="smallItem">
                <img id="itemImage2" src="<%= user_items.first.picture_url.thumb.url if user_items.first%>" alt="Image">
              </figure>
            </div>
        </div>
        <div class="range range-primary" style="margin-top: 20px">
            <label for="slider">Distance  <i class="fa fa-map-marker fa-lg"></i></label>
            <input id="slider" type="range" name="range" min="1" max="100" value="50" onchange="rangePrimary.value=value">
            <output id="rangePrimary">50</output>Km
          </div>
        <div class="notification is-primary" style="margin-top: 20px">
          <h1 class="title is-2" id="itemTitle"> </h1>
          <p id="itemDescription"> </p>

          <p class="title" id="itemTitle">  </p>
        </div>
        <div class="card is-fullwidth" id="inner">
          <div class="cardstatus">
          </div>
          <figure class="card-image is-4x3" id="bigItem">
            <img id="itemImage"  >
          </figure>
          <div class="card-content">
            <div class="content">
              <div class="columns">
                <div class="column is-half is-offset-quarter">
                  <a id="like" class="button is-success is-large"><i class="fa fa-check"></i>LIKE</a>
                  <a id="nope" class="button is-danger is-large"><i class="fa fa-times"></i>NOPE</a>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
    <%= render 'form' %>
    <%= render 'match_form' %>
  </body>
  </html>